POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John",
  "number": "043-123-4567"
}

###
# duplicate person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John",
  "number": "043-123"
}

###
# missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "043-123-4567"
}

###
# test post
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Danny",
  "number": "321"
}

###
# violation of minLength
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "D",
    "number": "1234567"
}

###
# check update using put
PUT http://localhost:3001/api/persons/61f21c3584d360739ddaf909
Content-Type: application/json

{
  "name": "Kobe",
  "number": "81"
}

###
# new post
POST https://infinite-ridge-50582.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Johnny",
  "number": "55"
}

###
# new post
POST https://infinite-ridge-50582.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "Kobe",
  "number": "567"
}

###
# updated number in person using put
PUT https://infinite-ridge-50582.herokuapp.com/api/persons/61f21c3584d360739ddaf909
Content-Type: application/json

{
  "name": "Kobe",
  "number": "123"
}

###
# new post
POST https://infinite-ridge-50582.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Salah",
  "number": "11"
}


